name: Validate

on: [pull_request_target]

jobs:
  validate_images:
    name: Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.number }}/merge
      - name: Validate images
        uses: ./.github/workflows/validate
  validate_manifest:
    name: Manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.number }}/merge
      - name: Get changed files
        #uses: lots0logs/gh-action-get-changed-files@2.1.4
        uses: Mineflash07/gh-action-get-changed-files@feature/support-pr-target-event # Remove as soon as PR is merged
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add json
        run:
          cp ${HOME}/files.json ./
      - name: Validate manifest
        uses: LabyMod/server-media/.github/workflows/validate-manifest@main
        env:
          PR_ID: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
